### ISSUE TITLE
TeamMate regularly consumes almost 1GB of memory within few seconds of starting

### ISSUE THREAD

**Issue by rahul-ramadas** [microsoft/TeamMate#100]
When I start TeamMate, it starts off consuming about 100MB of commit and active memory, and over the next few seconds, it climbs up to ~1GB and stays there forever. Is this by design? It almost feels like a memory leak. I only track 3 queries, each with about 30 results.

0.1.8-tags-0-1-8-ci-3-Branch-main-Sha-f818e18937ff8f2244f28c2674f83804f961e4ed.1+Branch.tags-0.1.8-ci.3-Branch.main.Sha.f818e18937ff8f2244f28c2674f83804f961e4ed.Sha.f818e18937ff8f2244f28c2674f83804f961e4ed

![image](https://github.com/microsoft/TeamMate/assets/2167984/618495f8-c993-476f-aea7-aaaf9dad722d)

**Comment by supermem613** [comment]
@rahul-ramadas, @erikpe-msft, can you please upgrade to 0.1.9 and grab a dump? Thank you!

**Comment by supermem613** [comment]
Regression from https://github.com/microsoft/TeamMate/pull/91. We are caching too much data for PRs.

**Comment by supermem613** [comment]
@rahul-ramadas, @erikpe-msft, release 0.1.10 has the fix.

**Comment by ivanv-microsoft** [comment]
[like]  Vanya Kashperuk reacted to your message:
________________________________
